/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg_sipenjualan;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import penjualan.view.bukuView;
import penjualan.view.loginView;
import penjualan.view.pelangganView;

/**
 * 985
 * @author irfan
 */
public class FPenjualan extends javax.swing.JFrame {

    /**
     * Creates new form FPenjualan
     */
    public FPenjualan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        menuPenjualan = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        masterPelanggan = new javax.swing.JMenuItem();
        masterBuku = new javax.swing.JMenuItem();
        userLogout = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("APLIKASI PENJUALAN");
        setName("framePenjualan"); // NOI18N

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Aplikasi Penjualan Buku");

        jLabel2.setText("DIbuat oleh :");

        jLabel6.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel6.setText("Achmad Imannudin");

        jLabel7.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel7.setText("Al Faisal Dwi Hariyanto");

        jLabel8.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel8.setText("Nisrina Qurrotul Ain");

        menuFile.setMnemonic('h');
        menuFile.setText("MENU");
        menuFile.setToolTipText("Ke Halaman Utama");
        menuFile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        masterPelanggan.setText("Pelanggan");
        masterPelanggan.setToolTipText("Master Pelanggan");
        masterPelanggan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        masterPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masterPelangganActionPerformed(evt);
            }
        });
        menuFile.add(masterPelanggan);

        masterBuku.setText("Buku");
        masterBuku.setToolTipText("Master Barang");
        masterBuku.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        masterBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masterBukuActionPerformed(evt);
            }
        });
        menuFile.add(masterBuku);

        userLogout.setText("Keluar");
        userLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userLogoutActionPerformed(evt);
            }
        });
        menuFile.add(userLogout);

        menuPenjualan.add(menuFile);

        setJMenuBar(menuPenjualan);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(80, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(71, 71, 71))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleDescription("Form Aplikasi Penjualan");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void masterBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masterBukuActionPerformed
        // TODO add your handling code here:
        bukuView tampilBarang = new bukuView();
        tampilBarang.setLocationRelativeTo(null);
        tampilBarang.setVisible(true);
    }//GEN-LAST:event_masterBukuActionPerformed

    private void masterPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masterPelangganActionPerformed
        // TODO add your handling code here:
        pelangganView tampilPelanggan = new pelangganView();
        tampilPelanggan.setLocationRelativeTo(null);
        tampilPelanggan.setVisible(true);
    }//GEN-LAST:event_masterPelangganActionPerformed

    private void userLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userLogoutActionPerformed
        this.dispose();
        loginView logout = new loginView();
        logout.setLocationRelativeTo(null);
        logout.setVisible(true);
    }//GEN-LAST:event_userLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FPenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FPenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FPenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FPenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FPenjualan().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem masterBuku;
    private javax.swing.JMenuItem masterPelanggan;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenuBar menuPenjualan;
    private javax.swing.JMenuItem userLogout;
    // End of variables declaration//GEN-END:variables
}
